### ISSUE TITLE
Simpler configuration with reflection

### ISSUE THREAD

**Issue by unkind** [SimpleBus/SymfonyBridge#39]
Hi,

http://simplebus.github.io/SymfonyBridge/doc/event_bus_bundle.html

As far as I can see from the doc above, if I need to register listener, I have to write something like
```yml
services:
    user_registered_event_subscriber:
        class: Acme\Listeners\SendEmailVerificationInstructionsSubscriber
        tags:
            - { name: event_subscriber, subscribes_to: Acme\Events\UserRegistered, method: onUserRegistered  }
            - { name: event_subscriber, subscribes_to: Acme\Events\UserChangedEmail, method: onUserChangedEmail }
```
for the given class:
```php
final class SendEmailVerificationInstructionsSubscriber
{
    public function onUserRegistered(UserRegistered $event)
    {
        // ...
    }

    public function onUserChangedEmail(UserChangedEmail $event)
    {
        // ...
    }    
}
```

Do I understand right, that the SymfonyBridge doesn't provide way to register all methods via reflection yet? I mean, you copy-paste method names and event classes into configuration, but in most cases it can be done automatically (well, for class-based naming strategy at least):
```yml
services:
    user_registered_event_subscriber:
        class: Acme\Listeners\SendEmailVerificationInstructionsSubscriber
        tags:
            - { name: event_subscriber, auto: true }
```
