### ISSUE TITLE
EventBus Subscribers not working with notify method

### ISSUE THREAD

**Issue by gubler** [SimpleBus/SymfonyBridge#74]
When I use the EventBus in a Symfony 4 app with autowiring, I have to use `__invoke()` for the method to be called in the subscriber. However, the docs state that I _should_ be able to use either `__invoke` or `notify`.

Is this wrong in the documentation, or is there some configuration I'm missing.

My service declaration:
```yaml
    App\Domain\Subscriber\:
        resource: '../src/Domain/Subscriber'
        tags: [event_subscriber]
        public: true
```

And my event subscriber (this is edited for brevity):
```php
<?php

namespace App\Domain\Subscriber\Project\Issue;

use App\Domain\Event\Project\Issue\IssueCreatedEvent;

class IssueCreatedEventSubscriber
{
    public function __notify(IssueCreatedEvent $event): void
    {
        // ... code that does stuff when event is received
    }
}
```

This works, but if I change ```public function __invoke(IssueCreatedEvent $event): void``` to ```public function notify(IssueCreatedEvent $event): void```, the event subscriber is no longer called.

Digging in a little deeper, it looks to be something with how the EventBusBridge compiler pass is looking for Event Subscribers. When I run ```bin/console debug:container IssueCreatedEventSubscriber```, I can see the ```event_subscriber``` tag, but if I change the method to ```notify```, the tag is no longer applied to the service.

I'm not sure what the difference is between the EventBusBridge compiler pass and the CommandBusBridge compiler pass. My command handlers work with both ```__invoke``` and ```handle```.

When I look in ```SimpleBusEventBusBundle.php```, I see the following:

```php
$container->addCompilerPass(
    new RegisterSubscribers(
        'simple_bus.event_bus.event_subscribers_collection',
        'event_subscriber',
        'subscribes_to'
    )
);
```

I tried changing ```__invoke``` to either ```subscribes_to``` or ```subscribesTo```, but neither worked.

So, is this a bug, an error in documentation (and I have to use __invoke), or am I messing something up?

And if it is an error in documentation, why can we use ```handle``` in command handlers, but not ```notify``` in event subscribers?

**Comment by cmodijk** [comment]
Hi @gubler thanks for taking the time to create this issue.

> This works, but if I change public function __invoke(IssueCreatedEvent $event): void to public function notify(IssueCreatedEvent $event): void, the event subscriber is no longer called.

The `notify` should only work if you subscribe to a specific event like this with a specific class.

```
services:
    user_registered_event_subscriber:
        class: Fully\Qualified\Class\Name\Of\UserRegisteredEventSubscriber
        tags:
            - { name: event_subscriber, subscribes_to: Fully\Qualified\Class\Name\Of\UserRegistered }
```

http://docs.simplebus.io/en/latest/Symfony/event-bus-bundle.html#setting-the-event-name-resolving-strategy

> And if it is an error in documentation, why can we use handle in command handlers, but not notify in event subscribers?

You are using the autowire feature and the default behaviour is to only use the `__invoke` in that case. If you want any public method to be subscribed you can use the `register_public_methods` option like this;

```
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Subscriber\:
        resource: '%kernel.project_dir%/src/Subscriber'
        public: true
        tags: [{ name: 'event_subscriber', register_public_methods: true }]
```

http://docs.simplebus.io/en/latest/Symfony/event-bus-bundle.html#one-subscriber-listening-to-multiple-events
